DATA_PATH = "~/data/rea_rag/downloaded_data"
CHROMA_DB_PATH = "~/data/rea_rag/chroma"
CHROMA_COLLECTION_NAME = "melbourne"
SENTENCE_TRANSFORMER_MODEL = "all-MiniLM-L6-v2"
LOG_RAG = "~/data/rea_rag/logs/rag.log"
LOG_INGEST = "~/data/rea_rag/logs/download_data.log"
